<?php

include_once('page_images_videos.features.inc');


/**
 * Implementation of hook_init().
 */
function page_images_videos_init() {
  drupal_add_css(drupal_get_path('module', 'page_images_videos') .'/theme/page-images-videos.css');
}

function page_images_videos_form_page_node_form_alter(&$form, &$form_state) {
  $form['#after_build'][] = 'page_images_videos_after_build';
}

// , or <a href="http://media.oregonstate.edu/" target="_blank">MediaSpace</a> code for media space

function page_images_videos_after_build(&$form, &$form_state) {
		$form['field_page_videos']['#description'] = 'Add videos from <a href="http://youtube.com/" target="_blank">YouTube</a>, or <a href="http://vimeo.com/">Vimeo</a>, or <a href="http://media.oregonstate.edu/" target="_blank">MediaSpace</a>. View instructions on <a href="http://extension.oregonstate.edu/help/quick-reference-guide#video_instructions">how to add videos</a>.';
	  $keys = array_filter(array_keys($form['field_page_videos']), 'page_images_videos_numeric_filter');
	  foreach ($keys as $key) {
			unset($form['field_page_videos'][$key]['embed']['#description']);
			unset($form['field_page_videos'][$key]['emvideo']['title']['#description']);
			unset($form['field_page_videos'][$key]['emvideo']['delete']['#description']);
			$form['field_page_videos'][$key]['emvideo']['title']['#title'] = 'Title';
			$form['field_page_videos'][$key]['emvideo']['delete']['#title'] = 'Delete this video';
			$form['field_page_videos'][$key]['embed']['#title'] = 'URL';
		  $form['field_page_videos'][$key]['embed']['#weight'] = '1';
			$form['field_page_videos'][$key]['value_markup']['#value'] = '<span class="media-id">' . $form['field_page_videos'][$key]['value_markup']['#value'] . '</span>';
			$form['field_page_videos'][$key]['value_markup']['#weight'] = '2';
	  }
	  $keys = array_filter(array_keys($form['field_page_images']), 'page_images_videos_numeric_filter');
	  foreach ($keys as $key) {
	    preg_match('/\<a\s(.*?)\<\/a\>/', $form['field_page_images'][$key]['filefield_imce']['display_path']['#value'], $matches);
	    $imce_url = 'Upload an image or ' . str_replace('browse', 'click here', $matches['0']) . ' to use an image already on the server.';
	    if ($form['field_page_images'][$key]['#value']['filepath'] == '') $form['field_page_images'][$key]['filefield_sources_list']['#value'] = $imce_url;
	    if ($form_state['clicked_button']['#value'] == 'Remove') $form['field_page_images'][$key]['filefield_sources_list']['#value'] = $imce_url;
	  }
	//dpm($form);
	  return $form;
}

function page_images_videos_numeric_filter($var) {
  if (is_numeric($var)) return TRUE;
}